name       : python-pytest-relaxed
version    : 1.1.5
release    : 4
source     :
    - https://github.com/bitprophet/pytest-relaxed/archive/1.1.5.tar.gz : 80ec97a6e220237b0fdb11ad0101005740bfe9855f0bc3851ac1e6ba1d5f7d95
homepage   : https://github.com/bitprophet/pytest-relaxed
license    : BSD-2-Clause
component  : programming.python
summary    : Relaxed test discovery for pytest
description: |
    pytest-relaxed provides 'relaxed' test discovery for pytest.
builddeps  :
    - python-decorator # check
    - python-pytest    # check
rundeps    :
    - python-decorator
    - python-pytest
setup      : |
    # Remove hardcoded dep requirements
    sed -i setup.py -e 's:pytest>=3,<5:pytest>=3:' -e 's:decorator>=4,<5:decorator>=4:'
    %patch -p1 < $pkgfiles/10.patch
    %patch -p1 < $pkgfiles/pytest-6.1-and-7.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
