name       : python-pytest-relaxed
version    : 2.0.1
release    : 6
source     :
    - https://github.com/bitprophet/pytest-relaxed/archive/2.0.1.tar.gz : caf4a7da34e922c0cd26fbf37b9aca1bc099a02668bcf83ebf6fe6717687e844
homepage   : https://github.com/bitprophet/pytest-relaxed
license    : BSD-2-Clause
component  : programming.python
summary    : Relaxed test discovery for pytest
description: |
    pytest-relaxed provides 'relaxed' test discovery for pytest.
builddeps  :
    - python-decorator # check
    - python-pytest    # check
rundeps    :
    - python-decorator
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
